-- MySQL Script generated by MySQL Workbench
-- 10/16/16 19:45:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
-- Schema used with the Ecommerce application
DROP SCHEMA IF EXISTS `ecommerce` ;

-- -----------------------------------------------------
-- Schema ecommerce
--
-- Schema used with the Ecommerce application
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`e_tbl_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`e_tbl_cliente` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`e_tbl_cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `ciudad_region` VARCHAR(2) NOT NULL,
  `cc_numero` VARCHAR(19) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`e_tbl_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`e_tbl_categoria` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`e_tbl_categoria` (
  `id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`e_tbl_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`e_tbl_producto` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`e_tbl_producto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(5,2) NOT NULL,
  `descripcion` TINYTEXT NULL,
  `ultima_modificacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `e_tbl_categoria_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_e_tbl_producto_e_tbl_categoria_idx` (`e_tbl_categoria_id` ASC),
  CONSTRAINT `fk_e_tbl_producto_e_tbl_categoria`
    FOREIGN KEY (`e_tbl_categoria_id`)
    REFERENCES `ecommerce`.`e_tbl_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`e_tbl_orden_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`e_tbl_orden_cliente` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`e_tbl_orden_cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(6,2) NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `numero_confirmacion` INT UNSIGNED NOT NULL,
  `e_tbl_cliente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_e_tbl_orden_cliente_e_tbl_cliente1_idx` (`e_tbl_cliente_id` ASC),
  CONSTRAINT `fk_e_tbl_orden_cliente_e_tbl_cliente1`
    FOREIGN KEY (`e_tbl_cliente_id`)
    REFERENCES `ecommerce`.`e_tbl_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`e_tbl_producto_solicitado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`e_tbl_producto_solicitado` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`e_tbl_producto_solicitado` (
  `e_tbl_producto_solicitado_orden_cliente` INT UNSIGNED NOT NULL,
  `e_tbl_producto_solicitado_producto` INT UNSIGNED NOT NULL,
  `cantidad` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`e_tbl_producto_solicitado_orden_cliente`, `e_tbl_producto_solicitado_producto`),
  INDEX `fk_e_tbl_orden_cliente_has_e_tbl_producto_e_tbl_producto1_idx` (`e_tbl_producto_solicitado_producto` ASC),
  INDEX `fk_e_tbl_orden_cliente_has_e_tbl_producto_e_tbl_orden_clien_idx` (`e_tbl_producto_solicitado_orden_cliente` ASC),
  CONSTRAINT `fk_e_tbl_orden_cliente_has_e_tbl_producto_e_tbl_orden_cliente1`
    FOREIGN KEY (`e_tbl_producto_solicitado_orden_cliente`)
    REFERENCES `ecommerce`.`e_tbl_orden_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_e_tbl_orden_cliente_has_e_tbl_producto_e_tbl_producto1`
    FOREIGN KEY (`e_tbl_producto_solicitado_producto`)
    REFERENCES `ecommerce`.`e_tbl_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
